version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_network

  python-app:
    image: python:3.9-slim
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://your_user:your_password@postgres:5432/your_database
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && python app.py"
    ports:
      - "9000:9000"  # Expose Tornado's port 9000 to the host machine
    networks:
      - internal_network

volumes:
  postgres_data:

networks:
  internal_network:
    driver: bridge

